name: SIMPLE FORTUNE COOKIE CI new
on: 
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main
env: # Set the secret as an input
  docker_username: ${{ secrets.DOCKER_USERNAME }}
  docker_password: ${{ secrets.DOCKER_TOKEN  }}
  GIT_COMMIT: ${{ github.sha }}
jobs:
  Clone-down:
    runs-on: self-hosted
    steps:
      - name: Clone-down
        uses: actions/checkout@v2
      - name: Upload Repo
        uses: actions/upload-artifact@v2
        with:
            name: code
            path: .
  Build:
      needs: Clone-down
      runs-on: self-hosted
      container: golang:latest
      steps:
        - name: Download Repo
          uses: actions/download-artifact@v2
          with:
            name: code
            path: .
        - name: setup
          run:  export GOPATH=$HOME/work && export PATH=$PATH:/usr/local/go/bin:$GOPATH/bin
        - name: Build
          run:  cd backend && go build . && cd ../frontend && go build .
        - name: Test
          run:  cd frontend && go test
        - name: Upload Repo
          uses: actions/upload-artifact@v2
          with:
            name: code
            path: .
  Docker-image:
      runs-on: self-hosted
      needs: [Build]
      steps:
        - name: Download code
          run: ls
        - name: build docker
          run: chmod +x ci/build-docker.sh && ci/build-docker.sh
        - name: push docker
          run: chmod +x ci/push-docker.sh && ci/push-docker.sh



    
        

        
        
